// Generates build/robots.txt so that crawlers can find the sitemap and
// the public demo pages. The site is served from a subpath on GitHub
// Pages, so the sitemap URL is absolute.
const fs = require('fs');
const path = require('path');

const SITE_URL = 'https://foxhound87.github.io/mobx-react-form-demo';

const content = `# robots.txt for ${SITE_URL}
# Generated by scripts/generate-robots.js
User-agent: *
Allow: /
Disallow: /assets/

Sitemap: ${SITE_URL}/sitemap.xml
`;

const outDir = path.resolve(__dirname, '..', 'build');
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const outFile = path.join(outDir, 'robots.txt');
fs.writeFileSync(outFile, content);
console.log(`Generated ${outFile}`);
